# Form implementation generated from reading ui file 'bookcode.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore,QtGui,QtWidgets
from CodeDock.C_Widgets.Custom import Custom
#from CodeDock.Dock.src.views.DockUi import Dock_Ui
#from CodeDock.Code.src.views.CodeUi import Code_Ui
class Code_Dock_Ui(object):
    def __init__(self):

        self.MainWindow=Custom.MainWindow()
        #self.MainWindow.show()
        self.MainWindow.setObjectName("CodeDock")
        self.MainWindow.resize(960, 550)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_centralw = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_centralw.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_centralw.setObjectName("gridLayout_4")
        self.main_widget = QtWidgets.QWidget()
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_mainw = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_mainw.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mainw.setSpacing(0)
        self.gridLayout_mainw.setObjectName("gridLayout_3")
        #self.main_splitter = QtWidgets.QSplitter(parent=self.main_widget)
        #self.splitter.setObjectName("Splitter")
        #self.splitter.setStyleSheet("Splitter{background-color:black;}")
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.main_splitter.sizePolicy().hasHeightForWidth())
        #self.main_splitter.setSizePolicy(sizePolicy)
        #self.main_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        #self.main_splitter.setSizes([100, 800])
        #self.splitter.setStyleSheet("background-color:white;")
        
        
        self.gridLayout_centralw.setSpacing(0)
        self.gridLayout_mainw.setSpacing(0)



        #self.gridLayout_mainw.addWidget(self.main_splitter, 0, 0, 1, 1)
        self.gridLayout_centralw.addWidget(self.main_widget, 0, 0, 1, 1)
        self.MainWindow.main_layout.addWidget(self.centralwidget)
        #self.centralLayout.addWidget(self.centralwidget)
        #self.retranslateUi(self.MainWindow)
        #QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

        
        #self.gridLayout_6.addWidget(self.color_widget_btn, 1, 3, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        """self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame_toolbox_a)
        self.pushButton_10.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_10.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")"""
        #self.gridLayout_6.addWidget(self.pushButton_10, 4, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        """self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_toolbox_a)
        self.pushButton_9.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_9.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")"""
        #self.gridLayout_6.addWidget(self.pushButton_9, 1, 1, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        """self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_toolbox_of_map)
        self.pushButton_2.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_2.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")"""
        #self.gridLayout_6.addWidget(self.pushButton_2, 1, 4, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        """self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_toolbox_a)
        self.pushButton_11.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_11.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        """

        """

        self.pushButton_3e = QtWidgets.QPushButton(parent=self.frame_toolbox_a)
        self.pushButton_3e.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_3e.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_3e.setText("")
        self.pushButton_3e.setObjectName("pushButton_3")
        """

        #self.gridLayout_6.addWidget(self.pushButton_11, 4, 4, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
        # Configure the grid layout
        # Adjust as necessary
        #self.frame_toolbox_of_map.setFixedHeight(33*10+20)
        
        #self.frame_toolbox_of_map.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        # Add buttons with left alignment
        
        #self.gridLayout_toolbox_a.addWidget(self.pushButton_9, 6, 0)
        #self.gridLayout_toolbox_a.addWidget(self.pushButton_10, 7, 0)
        #self.gridLayout_toolbox_a.addWidget(self.pushButton_11, 8, 0)
        #self.gridLayout_toolbox_a.addWidget(self.pushButton_3, 9, 0)        
        """self.pushButton_14 = QtWidgets.QPushButton(parent=self.frame_toolbox_of_editor)
        self.pushButton_14.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_14.setMaximumSize(QtCore.QSize(33, 33))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_3")
        
"""
        
        #self.gridLayout_7.addWidget(self.pushButton_14, 2, 0)
    #self.gridLayout_5.setColumnStretch(, )
    #self.gridLayout_5.setColumnStretch(0, 10)
    
    def retranslateUi(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("self.MainWindow", "self.MainWindow"))
      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Code_Dock_Ui(MainWindow)
   
    MainWindow.show()
    sys.exit(app.exec())
