# Form implementation generated from reading ui file 'color_s_d.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Setting_Dilaog(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("self")
        self.resize(650,450)
        self.main_layout=QtWidgets.QVBoxLayout()
        self.main_layout.setContentsMargins(0,0,0,0)
        self.setLayout(self.main_layout)
        self.splitter_2 = QtWidgets.QSplitter()
        self.main_layout.addWidget(self.splitter_2)
        #self.splitter_2.setGeometry(QtCore.QRect(0, 0, 1021, 641))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
            
        self.main_frame_1 = QtWidgets.QFrame(parent=self.splitter_2)
        self.main_frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame_1.setObjectName("frame_1_main")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_frame_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
       
        #self.gridLayout_3.addWidget(self.frame_1, 0, 0, 1, 1)

        self.frame_1 = QtWidgets.QFrame(parent=self.main_frame_1)
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_4")

        self.layout_frame_1=QtWidgets.QGridLayout(parent=self.frame_1)
        
        self.frame_1.setLayout(self.layout_frame_1)

        self.scroll_frame_1=QtWidgets.QScrollArea(self.main_frame_1)
        
        self.gridLayout_3.addWidget(self.scroll_frame_1,0,0)
        self.scroll_frame_1.setWidget(self.frame_1)
        self.scroll_frame_1.setWidgetResizable(True)
        self.wdgt=QtWidgets.QWidget()
        
        

        self.splitter = QtWidgets.QSplitter(parent=self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        #self.splitter.setObjectName("splitter")
        self.main_frame_2 = QtWidgets.QFrame(parent=self.splitter)
        self.main_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame_2.setObjectName("frame_2_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.main_frame_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_5")
        
        self.layout_frame_2=QtWidgets.QGridLayout(self.frame_2)
        
        self.frame_2.setLayout(self.layout_frame_2)

        self.scroll_frame_2=QtWidgets.QScrollArea(self.main_frame_2)
        
        self.gridLayout_2.addWidget(self.scroll_frame_2,0,0)
        self.scroll_frame_2.setWidget(self.frame_2)
        self.scroll_frame_2.setWidgetResizable(True)
        
        
        #self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        
        self.main_frame_3 = QtWidgets.QFrame(parent=self.splitter)
        self.main_frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame_3.setObjectName("frame_3_main")
        self.gridLayout = QtWidgets.QGridLayout(self.main_frame_3)
        self.gridLayout.setObjectName("gridLayout")
        #self.nested_widget = Custom.NestedMainWindow()
        #self.nested_widget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        #self.nested_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        #self.nested_widget.setObjectName("frame_6")

        #self.layout_frame_3=QtWidgets.QGridLayout(parent=self.nested_widget)
        #self.nested_widget.setLayout(self.layout_frame_3)
        
        #   self.gridLayout.addWidget(self.nested_widget, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)


        self.setStyleSheet(f"""
                QWidget{{
                    background-color:#272727;

                }}
                QScrollBar:vertical {{
                    background:#3F3F3F;      /* Scrollbar background */
                    border-radius: 4px;
                    
                    width: 10px;              /* Width of the scrollbar */
                    margin: 0px;               /* No margins */
                }}

                QScrollBar:horizontal {{
                    background:#3F3F3F;  /* Scrollbar background */
                    border-radius: 4px;
                    height: 10px;              /* Scrollbar height */
                    margin: 0px;              /* Margins around scrollbar */
                }}

                QScrollBar::handle:vertical {{
                    background:#A8A8A8;      
                    border-radius: 4px;       /* Rounded handle */
                    min-height: 20px;         /* Minimum height for usability */

                }}

                QScrollBar::handle:horizontal {{
                    background:#A8A8A8;      /* Scrollbar handle color (green) */
                    border-radius: 4px;       /* Rounded handle corners */
                    min-width: 20px;          /* Minimum handle width */
                }}
                           """)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()

    Form.setContentsMargins(0,0,0,0)
    ui = Setting_Dilaog(Form)
    #ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
