"""# Form implementation generated from reading ui file 'setting_cdbk.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1008, 600)
        self.main_layout=QtWidgets.QGridLayout()
        self.gridLayoutWidget = QtWidgets.QWidget()
        Dialog.setLayout(self.main_layout)
        self.main_layout.addWidget(self.gridLayoutWidget,0,0)
        #self.gridLayoutWidget.setGeometry(QtCore.QRect(-10, 0, 1021, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayoutWidget.setLayout(self.gridLayout)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")


        self.widget_layout=QtWidgets.QGridLayout()

        self.widget = QtWidgets.QWidget()
        self.widget.setLayout(self.widget_layout)
        
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget()
        self.widget_layout.addWidget(self.widget1,0,0)
        #self.widget1.setGeometry(QtCore.QRect(0, 0, 1021, 601))
        self.widget1.setObjectName("widget1")


        self.scroll_area= QtWidgets.QScrollArea()
        self.scroll_area.setWidgetResizable(True)

        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget1)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_2)
        #self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 761, 601))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        
        
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.scroll_area.setWidget(self.frame_2)
        self.gridLayout_2.addWidget(self.scroll_area, 0, 1, 1, 1)
        self.gridLayout_3.setContentsMargins(50, 50, 50, 50)
        self.gridLayout_3.setSpacing(50)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

class Theme_Selection(Ui_Dialog):
    def __init__(self,Dialog):

        super().__init__(Dialog)
        self.vertical_pos=0
        self.horizontal_pos=0
        self.total_wdgt=3


        theme_ls=["/home/omx/Pictures/Screenshot_20250318_185018.png",
                  "/home/omx/Pictures/Screenshot_20250318_184924.png",
                  "/home/omx/Pictures/Screenshot_20250318_184718.png",
                  "/home/omx/Pictures/Screenshot_20250318_184349.png",
                  "/home/omx/Pictures/Screenshot_20250318_184021.png",
                  "/home/omx/Pictures/Screenshot_20250318_185018.png",
                  "/home/omx/Pictures/Screenshot_20250318_184924.png",
                  "/home/omx/Pictures/Screenshot_20250318_184718.png",
                  "/home/omx/Pictures/Screenshot_20250318_184349.png",
                  "/home/omx/Pictures/Screenshot_20250318_184021.png",
                  "/home/omx/Pictures/Screenshot_20250318_185018.png",
                  "/home/omx/Pictures/Screenshot_20250318_184924.png",
                  "/home/omx/Pictures/Screenshot_20250318_184718.png",
                  "/home/omx/Pictures/Screenshot_20250318_184349.png",
                  "/home/omx/Pictures/Screenshot_20250318_184021.png"]
        for i,theme_img in enumerate(theme_ls):
            
            self.themes(i,theme_img)
    def btn_cn(self,path):
        print(path)

    def themes(self,i,path=None):
        self.themes_btns=QtWidgets.QPushButton()
        self.themes_btns.clicked.connect(lambda:self.btn_cn(i))
        #print(self.vertical_pos," ",self.horizontal_pos)
        self.gridLayout_3.addWidget(self.themes_btns,self.vertical_pos, self.horizontal_pos)
        self.themes_btns.setFixedHeight(175)
        self.themes_btns.setFixedWidth(300)
        if path!=None:
            self.themes_btns.setIcon(QtGui.QIcon(path))
        self.themes_btns.setIconSize(QtCore.QSize(350,400)) 

        self.horizontal_pos+=1
        if self.horizontal_pos>2:
            self.horizontal_pos=0
        if i>=self.total_wdgt:
            self.total_wdgt+=3
            self.vertical_pos+=1
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    o=Theme_Selection(Dialog)
    Dialog.show()
    
    sys.exit(app.exec())"""
import sys
from PyQt6.QtWidgets import (
    QApplication, QWidget, QLabel, QVBoxLayout,
    QScrollArea, QGridLayout
)
from PyQt6.QtGui import QPixmap, QMouseEvent
from PyQt6.QtCore import Qt, QTimer, pyqtSignal, QSize

MAX_IMAGE_SIZE = QSize(500,300)
MIN_IMAGE_WIDTH = 250
MARGIN = 10
SPACING = 10


class ClickableLabel(QLabel):
    
    def __init__(self, index, path,callable, parent=None):
        super().__init__(parent)
        self.index = index
        self.callable=callable
        self.path = path
        self.original_pixmap = QPixmap(path[0])
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setScaledContents(True)
        self.setFocusPolicy(Qt.FocusPolicy.StrongFocus)  # ← Accept keyboard focus
        self.setStyleSheet("border: 2px solid transparent;")

    def set_label_size(self, size: QSize):
        if not self.original_pixmap.isNull():
            scaled = self.original_pixmap.scaled(
                size,
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation
            )
            self.setPixmap(scaled)
            self.setFixedSize(size)

    def focusInEvent(self, event):
        self.setStyleSheet("border: 2px solid lightblue;") 
        self.callable(self.path[1])
        super().focusInEvent(event)

    def focusOutEvent(self, event):
        self.setStyleSheet("border: 2px solid transparent;")
        super().focusOutEvent(event)

    def keyPressEvent(self, event):
        if event.key() in (Qt.Key.Key_Enter, Qt.Key.Key_Return, Qt.Key.Key_Space):
            self.callable(self.path[1])

        else:
            super().keyPressEvent(event)

class ThemeListerWidget(QWidget):
    whenThemeSelect=pyqtSignal(object)
    def __init__(self, image_paths):
        super().__init__()
        self.image_paths = image_paths
        self.labels = []
        self.columns = 0

        self.scroll_area = QScrollArea(self)
        self.container = QWidget()
        self.grid = QGridLayout(self.container)
        self.grid.setContentsMargins(MARGIN, MARGIN, MARGIN, MARGIN)
        self.grid.setSpacing(SPACING)

        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setWidget(self.container)

        layout = QVBoxLayout(self)
        layout.addWidget(self.scroll_area)

        self.resize_timer = QTimer(self)
        self.resize_timer.setSingleShot(True)
        self.resize_timer.timeout.connect(self.populate_grid)

        self.init_labels()
        self.populate_grid()

    def theme_change_callable(self,path):
        self.whenThemeSelect.emit(path)

    def init_labels(self):
        for index, path in enumerate(self.image_paths):
            label = ClickableLabel(index, path,self.theme_change_callable)
            self.labels.append(label)

    def populate_grid(self):
        for i in reversed(range(self.grid.count())):
            widget = self.grid.itemAt(i).widget()
            if widget:
                widget.setParent(None)

        available_width = self.scroll_area.viewport().width() - 2 * MARGIN
        columns = max(1, available_width // (MIN_IMAGE_WIDTH + SPACING))
        self.columns = columns

        item_width = (available_width - ((columns - 1) * SPACING)) // columns
        image_width = min(item_width, MAX_IMAGE_SIZE.width())
        image_height = min(MAX_IMAGE_SIZE.height(), int(image_width * (MAX_IMAGE_SIZE.height() / MAX_IMAGE_SIZE.width())))
        image_size = QSize(image_width, image_height)

        for index, label in enumerate(self.labels):
            label.set_label_size(image_size)
            row = index // self.columns
            col = index % self.columns
            self.grid.addWidget(label, row, col)

    def resizeEvent(self, event):
        self.resize_timer.start(100)
        super().resizeEvent(event)

    def keyPressEvent(self, event):
        current = self.focusWidget()
        if not isinstance(current, ClickableLabel):
            return super().keyPressEvent(event)

        index = current.index
        rows = (len(self.labels) + self.columns - 1) // self.columns

        if event.key() == Qt.Key.Key_Right and index + 1 < len(self.labels):
            self.labels[index + 1].setFocus()
        elif event.key() == Qt.Key.Key_Left and index - 1 >= 0:
            self.labels[index - 1].setFocus()
        elif event.key() == Qt.Key.Key_Down and index + self.columns < len(self.labels):
            self.labels[index + self.columns].setFocus()
        elif event.key() == Qt.Key.Key_Up and index - self.columns >= 0:
            self.labels[index - self.columns].setFocus()
        else:
            super().keyPressEvent(event)

if __name__ == "__main__":
    app = QApplication(sys.argv)

    image_paths = [
        ["/home/omx/Pictures/Screenshot_20250318_185018.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184924.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184718.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184349.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184021.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_185018.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184924.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184718.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184349.png", 0],
        ["/home/omx/Pictures/Screenshot_20250318_184021.png", 0],
    ]

    window = ThemeListerWidget(image_paths)
    window.resize(1000, 800)
    window.setWindowTitle("Auto-Resizing Image Grid")
    window.show()

    sys.exit(app.exec())
